# Generated by Django 4.1.7 on 2023-03-26 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Day_And_Knights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='ecf_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='username',
            field=models.CharField(default='bedbca7cd03f4f79889a05d3715ec62f', max_length=150, unique=True),
        ),
    ]
