# Generated by Django 4.1.7 on 2023-04-25 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Day_And_Knights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='double_elimination_bracket_reset',
            field=models.BooleanField(default=True),
        ),
    ]
