# Generated by Django 4.1.7 on 2023-04-23 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Day_And_Knights', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='captain',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Day_And_Knights.player'),
        ),
        migrations.AlterField(
            model_name='team',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='home_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='home_field',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='players',
            field=models.ManyToManyField(blank=True, null=True, related_name='teams', to='Day_And_Knights.player'),
        ),
        migrations.AlterField(
            model_name='team',
            name='rank',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
