# Generated by Django 4.1.7 on 2023-03-25 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Day_And_Knights', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='league',
            name='teams',
        ),
        migrations.AddField(
            model_name='team',
            name='League',
            field=models.ManyToManyField(related_name='teams', to='Day_And_Knights.league'),
        ),
    ]
