# Generated by Django 4.1.7 on 2023-04-26 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Day_And_Knights', '0002_alter_team_captain_alter_team_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='user',
        ),
    ]
