# Generated by Django 4.1.7 on 2023-04-26 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Day_And_Knights', '0002_tournament_double_elimination_bracket_reset'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
