# Generated by Django 4.1.7 on 2023-03-25 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Day_And_Knights', '0003_alter_match_options_alter_team_team_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='round_number',
        ),
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
