# Generated by Django 4.1.7 on 2023-04-29 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Day_And_Knights', '0003_remove_player_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(choices=[('Home', 'Home_Team'), ('Away', 'Away_Team')], default='Home', max_length=4)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vounteers', to='Day_And_Knights.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteered', to='Day_And_Knights.player')),
            ],
        ),
        migrations.AddConstraint(
            model_name='volunteer',
            constraint=models.UniqueConstraint(fields=('match', 'player'), name='unique chapter'),
        ),
    ]
