# Generated by Django 4.1.7 on 2023-03-26 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Day_And_Knights', '0005_match_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='boards_per_match',
            field=models.IntegerField(default=6),
        ),
        migrations.AlterField(
            model_name='board',
            name='black_player',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='black_boards', to='Day_And_Knights.player'),
        ),
        migrations.AlterField(
            model_name='board',
            name='white_player',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='white_boards', to='Day_And_Knights.player'),
        ),
    ]
