# Generated by Django 4.1.7 on 2023-03-26 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Day_And_Knights', '0007_alter_board_black_player_alter_board_white_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='day_to_play',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='Wednesday', max_length=10),
        ),
    ]
